plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cadkey.notif2nas'
    compileSdk 34
    defaultConfig {
        applicationId "com.cadkey.notif2nas"
        minSdk 26
        targetSdk 34
        versionCode 305
        versionName "3.05"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-location:21.3.0'
}
